require_relative 'classes/modules/book_module'
require_relative 'classes/modules/label_module'
require_relative 'classes/modules/author_module'
require_relative 'classes/modules/game_module'
require_relative 'classes/modules/music_album_module'
require_relative 'classes/modules/genre_module'
